// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLqDCj3M3lfT1FQx6N6SGH99uCcrRLGeA',
    appId: '1:490578129393:web:45ed8a3c82f1dc822cd450',
    messagingSenderId: '490578129393',
    projectId: 'jur-gui',
    authDomain: 'jur-gui.firebaseapp.com',
    storageBucket: 'jur-gui.firebasestorage.app',
    measurementId: 'G-4SPSMP5PES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYF3q8cGzKui9X_bQ9Un21ot8HxFKZlTE',
    appId: '1:490578129393:android:0488b9e3de48dd932cd450',
    messagingSenderId: '490578129393',
    projectId: 'jur-gui',
    storageBucket: 'jur-gui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiUDvmwF1KWge-d6OcYki8nhWmi9i7qwc',
    appId: '1:490578129393:ios:d749d303dfd9cbb22cd450',
    messagingSenderId: '490578129393',
    projectId: 'jur-gui',
    storageBucket: 'jur-gui.firebasestorage.app',
    iosBundleId: 'com.te.depart',
  );
}
